import Head from 'next/head'
import {BsFillMoonStarsFill} from 'react-icons/bs'

export default function Home() {
  return (
    <div>
      <Head>
        <title>React Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10">
          <section className="min-h-screen">
            <nav  className="py-10 mb-12 flex justify-between">
              <h1 className="text-xl font-burtons">developedbyarince</h1>
              <ul className="flex items-center">
                <li> 
                  <BsFillMoonStarsFill className="cursor-pointer text-2xl" /></li>
                <li> 
                  <a className=" bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">Resume</a></li>
              </ul>
            </nav>
            <div>
              <h2>React Portfolio</h2>
              <h3>Developer and designer Web</h3>
              <p> Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of  sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
            </div>
          </section>
      </main>
    </div>
  )
}
